### ISSUE TITLE
Three args of BuildArrays.py do not function

### ISSUE THREAD

**Issue by quentinxs** [mathuin/TopoMC#13]
`maxdepth`, `sealevel`, and `slope` return invalid value errors when given.

Upon further investigation, the argument types each read off their respective check value function; whereas they should all read `type=int` and the validations should be with the rest in the block of code following the argument inputs.

Yes, I realize I solved the issue... I'm just too lazy to fork the project and then make a pull request.

**Comment by mathuin** [comment]
And they're fixed in the develop branch to boot. :-)  Well, I know the first two are, I don't know if I bothered with slope.

The develop branch will become the master branch as soon as pymclevel supports Anvil.  Thanks for noticing the problem and implementing a fix!  You're welcome to try the develop branch to see if it meets your needs for now!

Jack.
