### ISSUE TITLE
GPS coordinates from Google

### ISSUE THREAD

**Issue by noahtallen** [mathuin/TopoMC#40]
Hey, I'm just starting trying to use this. Here's the problem: how the heck do I get my x/y values from GPS coordinates? Google Maps has been updated, so apparently there is no way to select an area like is mentioned somewhere... I have Google earth and have the GPS coordinates of the two corners of the part of earth I wish to copy. (Gettysburgish area) How do I get those into a format useable by TopoMC? 

Here are the coordinates:
Corner 1:
lat: 39°48'25.81”N
long: 77°14'48.46”W

Corner 2:
lat: 39°46'33.36”N
long: 77°13'57.37"W

**Comment by mathuin** [comment]
You can no longer select an area in the new Google Maps, but you can right-click a point and select 'What's here' and it will return latlong values which TopoMC can use.  I just randomly clicked on part of Oregon and got 'Morrow County // OR // 45.397185, -119.836331'.  The first numeric value is the latitude and the second numeric value is the longitude.

But since you already have coordinates, let's discuss conversion.  The most important thing to keep in mind when converting coordinates is that North and East are positive in the decimal degrees system used by TopoMC, as the example above shows.

The format you have now is in degrees, minutes, and seconds.  There are sixty minutes in a degree, and sixty seconds in a minute.  The latitude for your first corner is equal to 39+48/60+25.81/3600 = 39.80717 while the longitude is -1*(77+14/60+48.46/3600) = -77.24679.

Let me know if this works for you, and I'll update the documentation accordingly.

**Comment by noahtallen** [comment]
Hi, thanks for the info about conversions! Earlier in the day, I basically changed it to a decimal.. So 39.482581 for the latitude, which is pretty similar to 39.80717.... kind of... I will try the real way, because I can't find the landmark I'm looking for (little round top). I have to use MCEdit to even see the world, but I don't think the way I did it worked. :) I will post back to let you know if it worked.

**Comment by noahtallen** [comment]
It worked :) thanks. I did end up getting new coordinates right from google.

**Comment by mathuin** [comment]
Awesome.  I'll update the documentation to reflect the new methods required, plus I'll add a link to a conversion site at the FCC:  http://transition.fcc.gov/mb/audio/bickel/DDDMMSS-decimal.html

Thanks for using TopoMC!
