### ISSUE TITLE
ValueError: need more than 1 value to unpack plus strange rendering behavior when successful.

### ISSUE THREAD

**Issue by dragos240** [mathuin/TopoMC#6]
Hello!

This error seems to be caused when running BuildArray.py with a scale and a vscale factor of 1.

Here's the output of ./BuildArrays.py --region GreatNeck --scale 1 --vscale 1 --disable-ore --disable-stats:

<pre><code>
Import error loading precompiled _nbt extension. Trying pyximport...
Accelerated NBT module loaded via pyximport.
../pymclevel/materials.py:152: UserWarning: Module argparse was already imported from /usr/lib64/python2.7/argparse.pyc, but /usr/lib64/python2.7/site-packages is being added to sys.path
  import pkg_resources
Processing region GreatNeck of size (134, 137) with 4 processes...
ERROR 2: Invalid dimensions : 8 x 0
Traceback (most recent call last):
  File "./BuildArrays.py", line 156, in <module>
    sys.exit(main(sys.argv))
  File "./BuildArrays.py", line 128, in main
    peaks = processTiles(args, minTileRows, maxTileRows, minTileCols, maxTileCols, processes)
  File "/home/harley/TopoMC/tile.py", line 167, in processTiles
    peaks = [x for x in results]
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 620, in next
    raise value
ValueError: need more than 1 value to unpack
</code></pre>

What's annoying here is that when proccessing regions in a large scale, it can take a while on the average computer to process the task, so it also takes a while to get the error.

The region "GreatNeck" was created by:
<code>./GetDataset.py --region GreatNeck --xmin -70.82 --xmax -70.78 --ymin 42.71 --ymax 42.68</code>

If anyone sees this. Try to run these commands yourself, if so, do you get the same error?

My python version is 2.7. I've created worlds with a scale factor of 6 (the default) with some odd behavior.
The strange behavior being if the world is imported to minecraft directly and run, the world will be overwritten with a random seed as if it had been generated with the ingame generator. If opened in MCEdit, the spawn point is near bedrock and at the very edge of the world, if you save the world in MCEdit, you will be able to use it in minecraft 1.0.0, however if the spawn is not changed, you will continue to fall off the world. I had done all of this and got some stranger behavior when minecraft was open. The issue is the area was generated correctly, but a seed was still used, this created an effect that looked like the far lands. When you reached the border of a world, the seed started to generate land high above the area.

If you need more output, or info. Please reply.

Thanks,
Dragos240

**Comment by dragos240** [comment]
2 more odd issues I've found as well.
- Slimes spawn EVERYWHERE on the surface, no idea why this is.
- Water appears in "speckles" for the lack of a better term. Its scattered in ugly 1x1x1 cubes throughout the landscape.

**Comment by mathuin** [comment]
Thank you for your report, especially for including the region!  When I built it at scale 1, I got the error you mentioned.  I then ran it with "--processes 1" to get the full error message:

```
Traceback (most recent call last):
  File "./BuildArrays.py", line 156, in <module>
    sys.exit(main(sys.argv))
  File "./BuildArrays.py", line 128, in main
    peaks = processTiles(args, minTileRows, maxTileRows, minTileCols, maxTileCols, processes)
  File "/home/jmt/git/TopoMC/tile.py", line 162, in processTiles
    peaks = [processTile(args, tileRowIndex, tileColIndex) for tileRowIndex in xrange(minTileRows, maxTileRows) for tileColIndex in xrange(minTileCols, maxTileCols)]
  File "/home/jmt/git/TopoMC/tile.py", line 122, in processTile
    bigImageArray = getImageArray(lcds, (depthUL, depthLR), depthArray, majority=True)
  File "/home/jmt/git/TopoMC/tile.py", line 62, in getImageArray
    IDT = getIDT(ds, Offset, Size, vScale, nodata, trim)
  File "/home/jmt/git/TopoMC/tile.py", line 41, in getIDT
    IDT = Invdisttree(LatLong, Value)
  File "/home/jmt/git/TopoMC/invdisttree.py", line 66, in __init__
    self.tree = KDTree( X, leafsize=leafsize )  # build the tree
  File "ckdtree.pyx", line 215, in scipy.spatial.ckdtree.cKDTree.__init__ (scipy/spatial/ckdtree.c:2186)
ValueError: need more than 1 value to unpack
```

I successfully generated your region at scale 2, which makes me think there aren't enough neighboring elevations at scale 1 to generate the inverse distance tree.  I will work on that!less or

There is something funky with the spawn point, I agree.  Not exactly sure why.  If you regenerate the world again, open it with something like Minutor to figure out where you want to spawn and then set it with MCEdit.  In the scale 2 world, I'd recommend 1655, 56, 536.  Also, before you actually enter the world in Minecraft, change the location of the player as well.  I think I know what's causing the spawn point problem.

The slime spawning thing appears to be a random chance thing according to this wiki page:  http://www.minecraftwiki.net/wiki/Slime#Spawning  Which reminds me, each world (generated by TopoMC or randomly) has a seed associated with it.  When you depart the limits of the terrain generated by TopoMC, the Minecraft server will generate additional terrain for you.  By default, TopoMC has a different definition of "sea level" than the Minecraft server, so the border will be a bit discontinuous.  Anyway, if you change the seed with MCEdit, the slimes shouldn't generate there anymore.

As for the speckled water, that's somewhat intentional.  When I generated your region at scale 6, I saw that 31% of your terrain had the landcover classification "emergent herbaceous wetlands".  Here's an example of herbaceous wetlands:  http://www.cbfwa.org/fwprogram/reviewcycle/fy2002cp/projects/extras/25098x/whr_cd/docs/defs/WHDF_H22.HTM  TopoMC generates this kind of terrain with a 80% grass/20% shallow water combination, which is why you see the "speckles".  If you want no water, change the "wetlandsgrass" variable (terrain.py:34) to 1.

I hope this helps!  Thank you again for using TopoMC.  I will let update this issue when the two problems discussed above are fixed.

Jack.

**Comment by dragos240** [comment]
Thank you on your quick reply. I have a suggestion though. What you are seeing with the wetlands is a marsh. We live right next to it. All of the herbaceous wetland pictures look very similar. My suggestion is to have TopoMC generate wheat instead to create the look of a marsh.

I understand why water generates as it does though now.

2 other suggestions that I have are as follows:
- Add a --noseed option, this would be useful for small areas that chunks would generate upon spawning.
- Add a --consistent option, this would keep landscape fairly consistent. I see right now that sometimes rock appears on the surface.

So far I find this a really great program! Keep up the good work :)

**Comment by mathuin** [comment]
One thing I want to add is stuff like flowers, tall grass, wheat and other surface items.  Those features were added after I started working on the software, and they're on my list to add.  The wheat would likely show up in "croplands" as defined by the landcover data, but I can see the marsh getting tall grass definitely.

You cannot really remove the seed.  If you don't include one, one will be generated for you by the server.  The only thing I can think that might help there would be to box in the world with bedrock or something to keep the other chunks out but that seems excessive.

The stone appears on the surface in rough approximation to the intensity of development in the area.  Places like roads or cities are usually nearly entirely covered with it.  The area you chose roughly ten percent of medium and low intensity development with a small portion of high intensity development according to the landcover data, which is why those parts of the map have stone on the surface.

Jack.

**Comment by dragos240** [comment]
That's interesting, about the seed. Do you know how other custom maps work? For example skyblock? If this is true, maybe they just placed air all around the area? Not sure though.

Thanks for the work!

**Comment by dragos240** [comment]
Just wondering. Has this been fixed and pushed to another branch? (ie. Develop)

Thanks,
Dragos

**Comment by mathuin** [comment]
I have been working on this issue and another issue that has been reported, and I have made some progress but not enough to update develop.  If you'd like to follow along, the branch is 'feature/regions'.  The command ./GetRegion.py is used to retrieve a region's mapping data from the USGS, and the command ./BuildRegion.py is used to actually build the region.  Parallelization is working pretty well and the spawn point problem has been solved, but the sun now rises from the south (blame Notch, he changed it in beta 19 prerelease 3) and there's two bits of oddness:  some scales don't work, and elevation's acting up.  You are hereby invited to tinker with the code and see if you can help with any of these issues. :-)  I am still working on it, don't worry. :-)

Jack.

**Comment by dragos240** [comment]
Thank you!

I will see if I can get git to let me switch branches. If I find a solution, I'll provide a diff of it.

**Comment by mathuin** [comment]
It should be as easy as "git pull; git checkout feature/regions".  Keep me up to date!  I will let you know if I make any more progress.

Jack.

**Comment by dragos240** [comment]
Worked now for whatever reason. Maybe I forgot to pull?

Either way. I've rendered the same area with the new commands and as you said, it does successfully build at scale 1 now, which is great, what I think is also great is that everything is dirt, so more time tweaking the code, and less processor time required to generate the world. Also the spawn works just fine now! No need to open mcedit anymore, thanks for that.

However, I can see what you mean by "the elevation's acting up". If I see something drastically wrong with your code, I may be able to help, but I'm not sure if I will. I don't know if I can help much, I'm only a beginner in the world of coding. :)

I'll show you what I mean:
http://imgur.com/a/2AtQk

A gallery of the region "GreatNeck". Same coordinates as posted last time, just put into the new commands and rendered with those.

Thanks for your hard work!

**Comment by mathuin** [comment]
Okay, I just pushed a new set of changes to feature/regions.  The sun should rise in the right place, arbitrary scales should work (I am still sticking to ones divisible by 30 for now), and elevation is now mostly under control.  There's also a minor speedup and smaller memory footprint to boot!

The most important result, however, is that I've replaced the bit of code that raised the error originally reported in this issue with calls to the GDAL binaries which do all the heavy lifting much better than my previous code ever did.  Additionally, the spawn point issue you mentioned in the original comment has also been fixed.

The biggest eyesore is the blockiness of the landcover.  This is most obvious at scale 1.  I am hoping to get that under control soon, but that may require modification to GDAL itself to add a new algorithm to the gdalwarp binary.

Other than that, I need to finish the vertical scale and trim feature and add functionality like terrain, ore, trees, and buildings which is already present in develop.  The hard part is done, though.

Jack.

**Comment by mathuin** [comment]
The refactoring of the maps code is complete, and the verdict is in: slow, but pretty.  The timing mentioned below is for the GreatNeck region mentioned above with scale 1, vscale 1, sealevel 8, maxdepth 4, trim 0.  This region contains 272 tiles, or about eighteen million blocks, so it's good for benchmarking.

There is a less-blocky approach to landcover, but it's resource-intensive.  I've added an internal geek knob to disable the code if blockiness is preferred to waiting longer and using more RAM.  Once gdalwarp supports the mode algorithm, I will automate the geek knob to bypass this code. The new landcover code takes about ten minutes and about 9G of RAM.

Generating the crust and bathy data on a region-wide basis is also resource-intensive.  For example, building the crust array takes about six minutes and uses over 8G of RAM.  It's prettier but gosh that's a lot of memory.  The bathy array is similar -- three minutes and over 9G of RAM -- as it requires the entire landcover array to be in memory.  Doing these things on the tile level would use less memory at the time but add more time overall, so it's a tradeoff.  I'll do some profiling to see which works best.

All three of these features lean heavily on the inverse distance trees, which were the source of the problem which generated this original issue.  While they're no longer used for elevation (which makes the original issue no longer happen), they are single-threaded and require the entire array to be loaded into memory to work.  There are other nearest-neighbor algorithms out there for Python and I will be trying others.

Also, this major change also fixed vertical scale and trim, and I'm about halfway through adding terrains.  Buildings, trees and ore should be placed on a per-region basis in order to avoid showing tile seams, but there might be a way to place the vast majority of the trees at the tile level and place any trees that cross tile borders at the region level.  Alas, can't really do that for ore -- and as buildings are pretty much the icing on the cake, they're done at the very end and in small enough numbers that I do not worry about them.

So!  The new code has been pushed to the repository.  Update your checkout, give it a spin, let me know what you think!  Once trees and ore are done, I'll be migrating this to the develop branch and preparing a release.

Jack.

**Comment by mathuin** [comment]
Trees and ore are done.  They have a performance impact associated with them -- ore more than trees -- so I'll be adding a --disable-ore flag to ./GetRegion.py but the code as such works fine.  If you want to disable ore by hand, replace oreObjs in newore.py with [] instead of what it has, and you should be okay.

One thing to keep in mind: lowering the sea level and trimming makes stuff like diamonds pop up near the surface, and also creates a huge deficit in things like coal and iron.  If you actually want to _play_ the level, you'll want to leave those settings at their defaults.

Jack.

**Comment by mathuin** [comment]
I have migrated the regions feature into develop, so I'm closing this issue.

Thank you again for posting the issue, and I hope the new code works well for you!

Jack.
