### ISSUE TITLE
World Height Increased!

### ISSUE THREAD

**Issue by ylluminate** [mathuin/TopoMC#8]
WONDERFUL NEWS: http://www.minecraftforum.net/news/404-new-snapshot-to-come-early-teaser-info-released/

• Maximum build height has been increased to 256 (was 128)

**Comment by mathuin** [comment]
I know right!  So exciting!

I've created an issue on pymclevel and updated another on c10t that I created a while ago.

Once pymclevel can support the larger worlds, I'll be adding the changes into the rewrite which is currently in progress.  That will probably be the gating factor on merging the rewrite into the develop branch, and preparing to release 1.0.

Thanks for creating an issue!  I should have done that myself. :-)

Jack.

**Comment by pm2845** [comment]
Just wondering if this has been addressed yet? Thanks!

**Comment by mathuin** [comment]
No, this issue hasn't yet been addressed.  The folks at c10t seem to be at an impasse, so I'm looking at Minecraft Overviewer as a potential substitute.  The real block for TopoMC at this point is pymclevel: until it gets updated for Anvil, I'm stuck.  I do not know of any alternative to pymclevel -- if there is one, please let me know!

Jack.

**Comment by mathuin** [comment]
There has been some good progress with c10t, but I'm still blocking on pymclevel.  They have partial Anvil support, but cannot yet create Anvil worlds.  Very frustrating! :-)

Anyway, just wanted to keep you guys up to date.

Jack.

**Comment by ylluminate** [comment]
Jack, it is indeed!  Thanks so much for keeping us in the loop.  You're doing a great job and we are really excited to see it when it finally pops out.  I've put any more work on that previous work I'd mentioned to you until we can get this new version since it will enrich the experience so much with the added height.

**Comment by mathuin** [comment]
I have submitted a bounty to the maintainer of pymclevel, and it has been accepted.  I've offered $50 to whoever can make pymclevel do what I need it to do for TopoMC, plus another $50 if it gets done by May 15.  Know anyone who can do the work? :-)

Jack.

**Comment by ylluminate** [comment]
Hey Jack, how's it going?  Unfortunately I've been buried in projects.  I have seen mention of anvil support it seems back in June? https://github.com/mcedit/pymclevel/commits/master 

Any news on that front?  Are we still waiting for something in that regard?

**Comment by mathuin** [comment]
The Anvil support for pymclevel is still not complete.

Based on that commit, it looks like Anvil worlds are now created by default, which is great news.

However, "python tests.py" in the pymclevel directory still fails.  It does fail differently, though, so I will check it out tonight and see whether there's enough working there for me to make some progress!

Jack.

**Comment by mathuin** [comment]
Okay, so I tested the new pymclevel and it's not yet ready for TopoMC.

It looks like only the region code changed.

To perform the test, I checked out the develop branch of TopoMC, ran 'git submodule init' and 'git submodule update' to retrieve pymclevel, and then changed to the pymclevel directory and ran 'git merge origin/master'.  Once this was done, I attempted to generate a world with vertical scale in excess of 128 to ensure it was working with 256-height worlds, and this failed.  TopoMC imports 'mclevel.MCInfdevOldLevel.Height' in region.py as its maximum height, and this was still set to 128.  I set it by hand in region.py to 256 and reran the program.  The tiles didn't take very long to build for Arecibo (only 16 tiles) but merging them took hours, so something wasn't right.  

I opened one of the tiles with mce.py and ran 'worldsize'.  Here's the output:

INFO:Identifying Regions/AreciboBig/Tiles/6169x-21/
INFO:Detected Infdev level.dat
INFO:Scanning for regions...
INFO:Found region file r.3084.-11.mca with 258/258 sectors used and 256 chunks present

World size: 
  1579520 north to south
     5392 east to west

Smallest and largest points: (0,-5376), (1579520,16)

The rest of the tiles were just as screwed up, which is why merging took forever.  The resulting map was impossible.

So, it looks like more work needs to be done on pymclevel so it can handle the Anvil map format more completely.  I documented the specific requirements in https://github.com/mcedit/pymclevel/issues/78 but so far nobody's bothered.  If there's an alternative to pymclevel out there that supports Anvil, I would love to give it a try.

Jack.

**Comment by ylluminate** [comment]
@mathuin I went ahead and posted this to [SO](http://stackoverflow.com/questions/12084739/minecraft-pymclevel-replacement-that-supports-anvil-maps) just in case others may be aware of other options for `pymclevel`.  Thanks very much for testing it out and getting some information back.  I'm hopeful we can find something satisfactory or perhaps someone will take some initiative and get `pymclevel` patched into shape.

**Comment by mathuin** [comment]
Thank you very much for posting!  I wish I'd thought of it five months ago... :-)

Jack.

**Comment by codewarrior0** [comment]
I tried to run from the dev branch of TopoMC but since the USGS servers are down, GetRegion.py couldn't get any data sets. I went ahead and copied the BlockIsland dataset from the master branch into the folder under Regions/BlockIsland/Datasets where it looked like it should go, and then ran PrepRegion.py. It looks like I did something wrong because the resulting Regions/BlockIsland/Map.tif is all black, and the generated tiles are nothing but 256x256 chunks of air. OTOH, they are all 256x256 chunks of air and not the 1.5 million blocks you got from running 'worldsize'

**Comment by mathuin** [comment]
I pulled down the current master branch of pymclevel, hand-set tileheight in region.py to 256, and ran ./PrepRegion.py on a small dataset I'd already retrieved before the USGS servers went down.  So far, the 256 bit looks good.  Map.tif does come out black because it's actually a four-level GeoTIFF and you need something like qgis to see all the layers.  ./BuildRegion.py is taking a loooong time with merging the 16 tiles.  When I looked at one of the tiles, this is what I saw with worldsize:

jmt@nala:~$ python ~/git/mathuin/TopoMC/pymclevel/mce.py git/mathuin/TopoMC/Regions/AreciboBig/Tiles/6169x-21/
INFO:Identifying git/mathuin/TopoMC/Regions/AreciboBig/Tiles/6169x-21/
INFO:Detected Infdev level.dat
6169x-21> worldsize

INFO:Scanning for regions...
INFO:Found region file r.3084.-11.mca with 258/258 sectors used and 256 chunks present

World size: 
  1579520 north to south
     5392 east to west

Smallest and largest points: (0,-5376), (1579520,16)
6169x-21>

**Comment by mathuin** [comment]
... just realized it's exactly the same dataset and tile that I used for the _last_ test.  Heh.  I scrounged around and found a dataset for Provincetown, and when I ran a tile of that one, I got a more sensible worldsize:

**Comment by mathuin** [comment]
... just realized it's exactly the same dataset and tile that I used for the _last_ test.  Heh.  I scrounged around and found a dataset for Provincetown, and when I ran a tile of that one, I got a more sensible worldsize:

World size: 
   348160 north to south
   399616 east to west

Smallest and largest points: (0,0), (348160,399616)

**Comment by codewarrior0** [comment]
Looks like a bug in MCInfdevOldWorld.getWorldBounds. It always thinks chunk 0,0 is in the bounds because of sloppy coding.

**Comment by mathuin** [comment]
I don't work with iterators much, but this crappy fix seems to give me reasonable numbers.

``` python
    achunks = iter(self.allChunks)
    achunk = achunks.next()
    mincx = achunk[0]
    maxcx = achunk[0]
    mincz = achunk[1]
    maxcz = achunk[1]
    try:
        achunk = achunks.next()
        mincx = min(mincx, achunk[0])
        maxcx = max(maxcx, achunk[0])
        mincz = min(mincz, achunk[1])
        maxcz = max(maxcz, achunk[1])
    except StopIteration:
        pass
```

It passes the worldsize test, anyway.  I'm not sure if this will help fix the problem I'm having where merging worlds takes way longer than it should, but I'm running a test now.

**Comment by mathuin** [comment]
I built a 99-tile world from the Provincetown region.  I used c10t to build a map of the area and the results came out... strange.  https://www.dropbox.com/s/dnh4ta7433e5yh6/StrangeProvincetown.png  I'm going to remove all the tiles and  redo it from scratch.

**Comment by codewarrior0** [comment]
Looks to me like that could be causing the problem, since those inflated bounds are being passed to `world.copyBlocksFrom` which then iterates over all the chunks in the bounds. The latest pymclevel has a better fix for getWorldBounds.

**Comment by mathuin** [comment]
@codewarrior0's changes to mcedit/pymclevel have done the trick.  I will be making some commits later this week and then rolling out a release.  Thank you very much for your help!

Jack.

**Comment by mathuin** [comment]
The release is out, so this issue is closed.

Jack.

**Comment by ylluminate** [comment]
Thank you!  Tremendous news @mathuin!
